# Can be set to "true" for correct compatibility with the Emojiful mod. Enabling this option:
# 1) Disables Discord Chat Mod's emoji suggestions to avoid conflicts with Emojiful
# 2) Disables Discord Chat Mod's rendering of custom Discord Emoji
# 3) Convert emoji sent from Discord to their names. For example, "😃" will be converted to ":smiley:"
emojifulCompatibility = false
# Maximum number of messages in the chat.
# When the number of messages exceeds this value, old messages are automatically deleted.
# By default, this value is 100 in the vanilla game.
#Range: > 20
maxChatHistory = 500

