"Enable Wither" = true
"Enable Ender Dragon" = true
"Enable Elder Guardian" = true

["Elder Guardian"]

	#Base feature for the Elder Guardian harder fights.
	["Elder Guardian".Base]
		#If true, the player will not be able to break blocks when an Elder Guardian is nearby. This also removes Mining Fatigue.
		"Adventure mode" = true
		#The range from any Elder Guardian at which players get adventure mode. This range is doubled when YUNG's Better Ocean Monuments is installed.
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		"Adventure mode Range" = 48.0

["Ender Dragon"]

	["Ender Dragon"."Ender Dragon Feature"]
		#Crystals can no longer be destroyed by other explosions.
		"Explosion Immune Crystals" = true
		#Enable some fixes for the Ender Dragon:
		# - Small spikes with cages now generate with obsidian on the corners to prevent cheesing.
		# - Dragon Head and Neck have been repositioned/resized correctly.
		# - Dragon will now play the growl sound only 4 times/second when respawning and when sitting instead of 20/second (so your ears shouldn't blow up anymore)
		# - When the crystals that respawn the dragon in the center are destroyed, the fire is extinguished
		# - Ender Dragon can now rise and fall faster (somewhere around 1.14 the multiplier for the y speed was reduced to 0.01 instead of 0.1 https://bugs.mojang.com/browse/MC-272431)
		# - Dragon is moved exactly at the center of the well when landed
		# - Fixes players accumulating knockback when hit by the dragon and then launching like a rocket
		# - Sets a portal cooldown to 4 years so she no longer goes through end gates
		"Enable Fixes" = true

